name: pangeo
channels:
 - conda-forge
dependencies:
 - python=3.7
 - pangeo-notebook=2020.07.18
 - bokeh=2.0
 - cartopy
 - datashader>=0.11
 - descartes
 - esmpy=7.1.0
 - fsspec
 - gcsfs
 - geopandas
 - geoviews-core
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - ipywidgets
 - ipyleaflet
 - jupyter-panel-proxy
 - lz4
 - matplotlib
 - matplotlib-base
 - metpy
 - nbserverproxy
 - nomkl
 - numpy
 - numcodecs
 - pandas
 - panel
 - prefect
 - pydap
 - python-blosc
 - rasterio
 - rio-cogeo
 - s3fs
 - sat-search
 - sat-stac
 - satpy
 - scikit-image
 - scikit-learn
 - scipy
 - sparse
 - tiledb-py
 - xarray
 - xpublish
# additional packages on top of pangeo notebook
 - zarr
 - eofs
 - xhistogram
 - xrft
 - cmip6_preprocessing
 - seaborn
 - nc-time-axis
 - xESMF
 - tqdm
 - basemap
 - gsw
 - pip:
   - git+https://github.com/xgcm/xgcm.git
   - git+https://github.com/pydata/xarray.git
   - git+https://github.com/JiaweiZhuang/xESMF.git
   - git+https://github.com/intake/filesystem_spec.git
   - sat-search
   - seawater
